AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Static Website Hosting

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: twentyseven
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadAccess
            Effect: Allow
            Principal: "*"
            Action: 
              - s3:GetObject
            Resource: !Sub "${MyS3Bucket.Arn}/*"

Outputs:
  WebsiteURL:
    Description: URL for website hosted on S3
    Value: !GetAtt MyS3Bucket.WebsiteURL

  BucketName:
    Description: Name of the S3 Bucket
    Value: !Ref MyS3Bucket

  BucketArn:
    Description: ARN of the S3 Bucket
    Value: !GetAtt MyS3Bucket.Arn
