name: Deploy Static Website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AKIA3C2RJ3BYFBEU456M }}
          aws-secret-access-key: ${{ secrets.tSJfAYR/9AgIIwDMdJx2Bis6S2xVdGRVrOG8AIu+}}
          aws-region: us-east-2

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://twentyseven --delete
