AWSTemplateFormatVersion: '2010-09-09'
Description: Static Website Hosting using S3 (bucket: twentyseven)

Resources:

  MyWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: twentyseven   # must be globally unique
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyWebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadAccess
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${MyWebsiteBucket.Arn}/*"

Outputs:

  WebsiteURL:
    Description: URL of the static website
    Value: !GetAtt MyWebsiteBucket.WebsiteURL

  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref MyWebsiteBucket
